<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EntitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('entities')->insert([
            'id' => 1,
            'name' => 'CmsPage',
            'slug' => 'cms-pages',
            'table' => 'cms_pages',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'cms',
            'orderable' => 'no',
            'orderable_key' => 'slug',
            'model' => 'Core\CMS\Models\CmsPage',
            'migration' => '',
            'table_filters' => '["slug","name","is_parent","details"]',
            'table_fields' => '["slug","name","is_parent"]',
            'api_fields_list' => '["slug","name","is_parent","is_multi_upload","have_point","have_name","have_description","have_intro","have_image","have_tablet_image","have_mobile_image","have_icon","have_video","have_link","details"]',
            'api_fields_single' => '["slug","name","is_parent","is_multi_upload","have_point","have_name","have_description","have_intro","have_image","have_tablet_image","have_mobile_image","have_icon","have_video","have_link","details"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:58',
        ]);
        DB::table('entities')->insert([
            'id' => 2,
            'name' => 'CmsPageDetail',
            'slug' => 'cms-page-details',
            'table' => 'cms_page_details',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'cms',
            'orderable' => 'no',
            'orderable_key' => 'name',
            'model' => 'Core\CMS\Models\CmsPageDetail',
            'migration' => '',
            'table_filters' => '["name","description","intro","point","image","tablet_image","mobile_image","icon","video","link","cms_pages_id"]',
            'table_fields' => '["name","image","mobile_image","icon","video","link","cms_pages_id"]',
            'api_fields_list' => '["name","description","intro","point","image","tablet_image","mobile_image","icon","video","link","cms_pages_id"]',
            'api_fields_single' => '["name","description","intro","point","image","tablet_image","mobile_image","icon","video","link","cms_pages_id"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:58',
        ]);
        DB::table('entities')->insert([
            'id' => 3,
            'name' => 'Country',
            'slug' => 'countries',
            'table' => 'countries',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'info',
            'orderable' => 'no',
            'orderable_key' => 'slug',
            'model' => 'Core\Info\Models\Country',
            'migration' => '',
            'table_filters' => '["slug","name","phonecode","short_name","flag"]',
            'table_fields' => '["slug","name","phonecode","short_name","flag"]',
            'api_fields_list' => '["slug","name","phonecode","short_name","flag","cities"]',
            'api_fields_single' => '["slug","name","phonecode","short_name","flag","cities"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:58',
        ]);
        DB::table('entities')->insert([
            'id' => 4,
            'name' => 'City',
            'slug' => 'cities',
            'table' => 'cities',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'info',
            'orderable' => 'no',
            'orderable_key' => 'slug',
            'model' => 'Core\Info\Models\City',
            'migration' => '',
            'table_filters' => '["slug","name","postal_code","image","delivery_price","status","country_id"]',
            'table_fields' => '["slug","name","postal_code","image","delivery_price","status","country_id"]',
            'api_fields_list' => '["slug","name","lat","lng","postal_code","image","delivery_price","status","country_id","districts"]',
            'api_fields_single' => '["slug","name","lat","lng","postal_code","image","delivery_price","status","country_id","districts"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 5,
            'name' => 'District',
            'slug' => 'districts',
            'table' => 'districts',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'info',
            'orderable' => 'no',
            'orderable_key' => 'slug',
            'model' => 'Core\Info\Models\District',
            'migration' => '',
            'table_filters' => '["slug","name","lat","lng","postal_code","city_id"]',
            'table_fields' => '["slug","name","lat","lng","postal_code","city_id"]',
            'api_fields_list' => '["slug","name","lat","lng","postal_code","city_id"]',
            'api_fields_single' => '["slug","name","lat","lng","postal_code","city_id"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 6,
            'name' => 'Permission',
            'slug' => 'permissions',
            'table' => 'permissions',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'users',
            'orderable' => 'no',
            'orderable_key' => 'title',
            'model' => 'Core\Users\Models\Permission',
            'migration' => '',
            'table_filters' => '[]',
            'table_fields' => '["title","name"]',
            'api_fields_list' => '["title","name"]',
            'api_fields_single' => '["title","name"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 7,
            'name' => 'Role',
            'slug' => 'roles',
            'table' => 'roles',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'users',
            'orderable' => 'no',
            'orderable_key' => 'title',
            'model' => 'Core\Users\Models\Role',
            'migration' => '',
            'table_filters' => '["title","name"]',
            'table_fields' => '["title","name"]',
            'api_fields_list' => '["title","name","permissions"]',
            'api_fields_single' => '["title","name","permissions"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 8,
            'name' => 'User',
            'slug' => 'users',
            'table' => 'users',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'users',
            'orderable' => 'no',
            'orderable_key' => 'image',
            'model' => 'Core\Users\Models\User',
            'migration' => '',
            'table_filters' => '["image","fullname","email","email_verified_at","phone","phone_verified_at","roles","is_active","is_allow_notify","date_of_birth","identity_number","wallet","gender","rate_avg","referral_code","verified_code","last_login_at"]',
            'table_fields' => '["image","fullname","email","phone","roles","is_active","is_allow_notify","date_of_birth","gender"]',
            'api_fields_list' => '["image","fullname","email","email_verified_at","phone","phone_verified_at","roles","is_active","is_allow_notify","date_of_birth","identity_number","wallet","gender","rate_avg","referral_code","verified_code","last_login_at"]',
            'api_fields_single' => '["image","fullname","email","email_verified_at","phone","phone_verified_at","roles","is_active","is_allow_notify","date_of_birth","identity_number","wallet","gender","rate_avg","referral_code","verified_code","last_login_at"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 9,
            'name' => 'UserEditRequest',
            'slug' => 'user-edit-requests',
            'table' => 'user_edit_requests',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'users',
            'orderable' => 'no',
            'orderable_key' => 'fullname',
            'model' => 'Core\Users\Models\UserEditRequest',
            'migration' => '',
            'table_filters' => '["fullname","email","phone","user_id"]',
            'table_fields' => '["fullname","email","phone","user_id"]',
            'api_fields_list' => '["fullname","email","phone","user_id"]',
            'api_fields_single' => '["fullname","email","phone","user_id"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 10,
            'name' => 'Profile',
            'slug' => 'profiles',
            'table' => 'profiles',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'users',
            'orderable' => 'no',
            'orderable_key' => 'country_id',
            'model' => 'Core\Users\Models\Profile',
            'migration' => '',
            'table_filters' => '["country_id","city_id","district_id","other_city_name","user_id","bio","lat","lng"]',
            'table_fields' => '["country_id","city_id","district_id","other_city_name","user_id","bio","lat","lng"]',
            'api_fields_list' => '["country_id","city_id","district_id","other_city_name","user_id","bio","lat","lng"]',
            'api_fields_single' => '["country_id","city_id","district_id","other_city_name","user_id","bio","lat","lng"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 11,
            'name' => 'Ban',
            'slug' => 'bans',
            'table' => 'bans',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'users',
            'orderable' => 'no',
            'orderable_key' => 'level',
            'model' => 'Core\Users\Models\Ban',
            'migration' => '',
            'table_filters' => '["level","value","admin_id","reason","from","to"]',
            'table_fields' => '["level","value","admin_id","reason","from","to"]',
            'api_fields_list' => '["level","value","admin_id","reason","from","to"]',
            'api_fields_single' => '["level","value","admin_id","reason","from","to"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 12,
            'name' => 'Device',
            'slug' => 'devices',
            'table' => 'devices',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'users',
            'orderable' => 'no',
            'orderable_key' => 'device_token',
            'model' => 'Core\Users\Models\Device',
            'migration' => '',
            'table_filters' => '["device_token","type","user_id"]',
            'table_fields' => '["device_token","type","user_id"]',
            'api_fields_list' => '["device_token","type","user_id"]',
            'api_fields_single' => '["device_token","type","user_id"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 13,
            'name' => 'Fav',
            'slug' => 'favs',
            'table' => 'favs',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'users',
            'orderable' => 'no',
            'orderable_key' => 'favs_type',
            'model' => 'Core\Users\Models\Fav',
            'migration' => '',
            'table_filters' => '["favs_type","favs_id","user_id"]',
            'table_fields' => '["favs_type","favs_id","user_id"]',
            'api_fields_list' => '["favs_type","favs_id","user_id"]',
            'api_fields_single' => '["favs_type","favs_id","user_id"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 14,
            'name' => 'Coupon',
            'slug' => 'coupons',
            'table' => 'coupons',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'coupons',
            'orderable' => 'no',
            'orderable_key' => 'code',
            'model' => 'Core\Coupons\Models\Coupon',
            'migration' => '',
            'table_filters' => '["code","minimum_price","discount_type","value","status","expired_at"]',
            'table_fields' => '["code","minimum_price","discount_type","value","status","expired_at"]',
            'api_fields_list' => '["code","minimum_price","discount_type","value","status","expired_at"]',
            'api_fields_single' => '["code","minimum_price","discount_type","value","status","expired_at"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 15,
            'name' => 'Nationality',
            'slug' => 'nationalities',
            'table' => 'nationalities',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'info',
            'orderable' => 'no',
            'orderable_key' => 'name',
            'model' => 'Core\Info\Models\Nationality',
            'migration' => '',
            'table_filters' => '["name","arranging"]',
            'table_fields' => '["name","arranging"]',
            'api_fields_list' => '["name","arranging"]',
            'api_fields_single' => '["name","arranging"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 16,
            'name' => 'Notification',
            'slug' => 'notifications',
            'table' => 'notifications',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'notification',
            'orderable' => 'no',
            'orderable_key' => 'types',
            'model' => 'Core\Notification\Models\Notification',
            'migration' => '',
            'table_filters' => '["types","for","title","body","media","sender_id"]',
            'table_fields' => '["types","for","title","body","media","sender_id"]',
            'api_fields_list' => '["types","for","for_data","title","body","media","sender_id"]',
            'api_fields_single' => '["types","for","for_data","title","body","media","sender_id"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 17,
            'name' => 'banner_notifications',
            'slug' => 'banner-notifications',
            'table' => 'banner_notifications',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'notification',
            'orderable' => 'no',
            'orderable_key' => 'image',
            'model' => 'Core\Notification\Models\BannerNotification',
            'migration' => '',
            'table_filters' => '["image","publish_date","expired_date","next_vision_hour","status"]',
            'table_fields' => '["image","publish_date","expired_date","next_vision_hour","status"]',
            'api_fields_list' => '["image","publish_date","expired_date","next_vision_hour","status"]',
            'api_fields_single' => '["image","publish_date","expired_date","next_vision_hour","status"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 18,
            'name' => 'WalletPackage',
            'slug' => 'wallet-packages',
            'table' => 'wallet_packages',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'wallet',
            'orderable' => 'no',
            'orderable_key' => 'image',
            'model' => 'Core\Wallet\Models\WalletPackage',
            'migration' => '',
            'table_filters' => '["image","price","value","status"]',
            'table_fields' => '["image","price","value","status"]',
            'api_fields_list' => '["image","price","value","status"]',
            'api_fields_single' => '["image","price","value","status"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 19,
            'name' => 'WalletTransaction',
            'slug' => 'wallet-transactions',
            'table' => 'wallet_transactions',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'wallet',
            'orderable' => 'no',
            'orderable_key' => 'type',
            'model' => 'Core\Admin\Models\WalletTransaction',
            'migration' => '',
            'table_filters' => '["type","amount","wallet_before","wallet_after","status","transaction_id","bank_name","account_number","iban_number","user_id","added_by_id","package_id"]',
            'table_fields' => '["type","amount","wallet_before","wallet_after","status","transaction_id","bank_name","account_number","iban_number","user_id","added_by_id","package_id"]',
            'api_fields_list' => '["type","amount","wallet_before","wallet_after","status","transaction_id","bank_name","account_number","iban_number","user_id","added_by_id","package_id"]',
            'api_fields_single' => '["type","amount","wallet_before","wallet_after","status","transaction_id","bank_name","account_number","iban_number","user_id","added_by_id","package_id"]',
            'created_at' => '2025-01-07 04:10:55',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 20,
            'name' => 'Category',
            'slug' => 'categories',
            'table' => 'categories',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'categories',
            'orderable' => 'no',
            'orderable_key' => 'slug',
            'model' => 'Core\Categories\Models\Category',
            'migration' => '',
            'table_filters' => '["name","intro","desc","type","sort","status","parent_id","city_id"]',
            'table_fields' => '["name","image","desc","type","delivery_price","sort","is_package","status","parent_id","city_id"]',
            'api_fields_list' => '["slug","name","image","intro","desc","type","delivery_price","sort","is_package","status","parent_id","city_id","sub_categories","category_types","category_settings"]',
            'api_fields_single' => '["slug","name","image","intro","desc","type","delivery_price","sort","is_package","status","parent_id","city_id","sub_categories","category_types","category_settings"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 21,
            'name' => 'CategoryDate',
            'slug' => 'category-dates',
            'table' => 'category_dates',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'categories',
            'orderable' => 'no',
            'orderable_key' => 'type',
            'model' => 'Core\Categories\Models\CategoryDate',
            'migration' => '',
            'table_filters' => '["type","category_id","date"]',
            'table_fields' => '["type","category_id","date"]',
            'api_fields_list' => '["type","category_id","date"]',
            'api_fields_single' => '["type","category_id","date"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 22,
            'name' => 'CategoryTime',
            'slug' => 'category-times',
            'table' => 'category_times',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'categories',
            'orderable' => 'no',
            'orderable_key' => 'category_id',
            'model' => 'Core\Categories\Models\CategoryTime',
            'migration' => '',
            'table_filters' => '["category_id","day","from","to"]',
            'table_fields' => '["category_id","day","from","to"]',
            'api_fields_list' => '["category_id","day","from","to"]',
            'api_fields_single' => '["category_id","day","from","to"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 23,
            'name' => 'CategoryDateTime',
            'slug' => 'category-date-times',
            'table' => 'category_date_times',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'categories',
            'orderable' => 'no',
            'orderable_key' => 'type',
            'model' => 'Core\Categories\Models\CategoryDateTime',
            'migration' => '',
            'table_filters' => '["type","category_id","date_id","from","to","order_count"]',
            'table_fields' => '["type","category_id","date_id","from","to","order_count"]',
            'api_fields_list' => '["type","category_id","date_id","from","to","order_count"]',
            'api_fields_single' => '["type","category_id","date_id","from","to","order_count"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 24,
            'name' => 'CategoryOffer',
            'slug' => 'category-offers',
            'table' => 'category_offers',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'categories',
            'orderable' => 'no',
            'orderable_key' => 'name',
            'model' => 'Core\Categories\Models\CategoryOffer',
            'migration' => '',
            'table_filters' => '["name","desc","price","sale_price","image","hours_num","workers_num","status","type"]',
            'table_fields' => '["name","price","sale_price","image","hours_num","workers_num","status","type"]',
            'api_fields_list' => '["name","desc","price","sale_price","image","hours_num","workers_num","status","type"]',
            'api_fields_single' => '["name","desc","price","sale_price","image","hours_num","workers_num","status","type"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 25,
            'name' => 'CategoryType',
            'slug' => 'category-types',
            'table' => 'category_types',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'categories',
            'orderable' => 'no',
            'orderable_key' => 'slug',
            'model' => 'Core\Categories\Models\CategoryType',
            'migration' => '',
            'table_filters' => '["slug","name","intro","desc","category_id","hour_price","status"]',
            'table_fields' => '["slug","name","intro","desc","category_id","hour_price","status"]',
            'api_fields_list' => '["slug","name","intro","desc","category_id","hour_price","status"]',
            'api_fields_single' => '["slug","name","intro","desc","category_id","hour_price","status"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 26,
            'name' => 'CategorySetting',
            'slug' => 'category-settings',
            'table' => 'category_settings',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'categories',
            'orderable' => 'no',
            'orderable_key' => 'slug',
            'model' => 'Core\Categories\Models\CategorySetting',
            'migration' => '',
            'table_filters' => '["slug","name","category_id","addon_price","parent_id","status","category_settings"]',
            'table_fields' => '["slug","name","category_id","addon_price","parent_id","status","category_settings"]',
            'api_fields_list' => '["slug","name","category_id","addon_price","parent_id","status","category_settings"]',
            'api_fields_single' => '["slug","name","category_id","addon_price","parent_id","status","category_settings"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 27,
            'name' => 'Slider',
            'slug' => 'sliders',
            'table' => 'sliders',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'categories',
            'orderable' => 'no',
            'orderable_key' => 'category_id',
            'model' => 'Core\Categories\Models\Slider',
            'migration' => '',
            'table_filters' => '["category_id","type","status","city_id"]',
            'table_fields' => '["category_id","type","status","city_id"]',
            'api_fields_list' => '["category_id","type","status","city_id"]',
            'api_fields_single' => '["category_id","type","status","city_id"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 28,
            'name' => 'Product',
            'slug' => 'products',
            'table' => 'products',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'products',
            'orderable' => 'no',
            'orderable_key' => 'name',
            'model' => 'Core\Products\Models\Product',
            'migration' => '',
            'table_filters' => '["name","desc","image","type","sku","is_package","category_id","sub_category_id","price","quantity","status"]',
            'table_fields' => '["name","images","type","sku","category_id","sub_category_id","price","quantity","status"]',
            'api_fields_list' => '["name","desc","image","type","sku","is_package","category_id","sub_category_id","price","quantity","status"]',
            'api_fields_single' => '["name","desc","image","type","sku","is_package","category_id","sub_category_id","price","quantity","status"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 29,
            'name' => 'Cart',
            'slug' => 'carts',
            'table' => 'carts',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'user_id',
            'model' => 'Core\Orders\Models\Cart',
            'migration' => '',
            'table_filters' => '["user_id","phone"]',
            'table_fields' => '["user_id","phone"]',
            'api_fields_list' => '["user_id","phone","data"]',
            'api_fields_single' => '["user_id","phone","data"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 30,
            'name' => 'Order',
            'slug' => 'orders',
            'table' => 'orders',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'reference_id',
            'model' => 'Core\Orders\Models\Order',
            'migration' => '',
            'table_filters' => '["reference_id","type","status","client_id","pay_type","transaction_id","note","coupon_id","order_price","delivery_price","total_price","paid","is_admin_accepted","admin_cancel_reason","wallet_used","wallet_amount_used"]',
            'table_fields' => '["reference_id","type","status","client_id","pay_type","note","coupon_id","total_price","paid","is_admin_accepted","admin_cancel_reason","wallet_used","wallet_amount_used"]',
            'api_fields_list' => '["reference_id","type","status","client_id","pay_type","transaction_id","order_status_times","days_per_week","days_per_week_names","days_per_month_dates","note","coupon_id","coupon_data","order_price","delivery_price","total_price","paid","is_admin_accepted","admin_cancel_reason","wallet_used","wallet_amount_used","items","representatives","reports"]',
            'api_fields_single' => '["reference_id","type","status","client_id","pay_type","transaction_id","order_status_times","days_per_week","days_per_week_names","days_per_month_dates","note","coupon_id","coupon_data","order_price","delivery_price","total_price","paid","is_admin_accepted","admin_cancel_reason","wallet_used","wallet_amount_used","items","representatives","reports"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 31,
            'name' => 'OrderRepresentative',
            'slug' => 'order-representatives',
            'table' => 'order_representatives',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'order_id',
            'model' => 'Core\Orders\Models\OrderRepresentative',
            'migration' => '',
            'table_filters' => '["order_id","representative_id","type","category_date_id","date","to_date","category_time_id","time","to_time","lat","lng","location","has_problem"]',
            'table_fields' => '["order_id","representative_id","type","date","time","to_time","location","has_problem"]',
            'api_fields_list' => '["order_id","representative_id","type","category_date_id","date","to_date","category_time_id","time","to_time","lat","lng","location","has_problem"]',
            'api_fields_single' => '["order_id","representative_id","type","category_date_id","date","to_date","category_time_id","time","to_time","lat","lng","location","has_problem"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 32,
            'name' => 'OrderTypesOfData',
            'slug' => 'order-types-of-datas',
            'table' => 'order_types_of_datas',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'order_id',
            'model' => 'Core\Orders\Models\OrderTypesOfDatum',
            'migration' => '',
            'table_filters' => '["order_id","key","value"]',
            'table_fields' => '["order_id","key","value"]',
            'api_fields_list' => '["order_id","key","value"]',
            'api_fields_single' => '["order_id","key","value"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 33,
            'name' => 'OrderItem',
            'slug' => 'order-items',
            'table' => 'order_items',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'order_id',
            'model' => 'Core\Orders\Models\OrderItem',
            'migration' => '',
            'table_filters' => '["order_id","product_id","product_price","quantity","carpet_size","add_by_admin","update_by_admin"]',
            'table_fields' => '["order_id","product_id","product_price","quantity","carpet_size","add_by_admin","update_by_admin"]',
            'api_fields_list' => '["order_id","product_id","product_name","product_data","product_price","quantity","carpet_size","add_by_admin","update_by_admin","qtyUpdates"]',
            'api_fields_single' => '["order_id","product_id","product_name","product_data","product_price","quantity","carpet_size","add_by_admin","update_by_admin","qtyUpdates"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:40:59',
        ]);
        DB::table('entities')->insert([
            'id' => 34,
            'name' => 'OrderItemQtyUpdate',
            'slug' => 'order-item-qty-updates',
            'table' => 'order_item_qty_updates',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'item_id',
            'model' => 'Core\Orders\Models\OrderItemQtyUpdate',
            'migration' => '',
            'table_filters' => '["item_id","from","to","updater_email"]',
            'table_fields' => '["item_id","from","to","updater_email"]',
            'api_fields_list' => '["item_id","from","to","updater_email"]',
            'api_fields_single' => '["item_id","from","to","updater_email"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:41:00',
        ]);
        DB::table('entities')->insert([
            'id' => 35,
            'name' => 'ReportReason',
            'slug' => 'report-reasons',
            'table' => 'report_reasons',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'name',
            'model' => 'Core\Orders\Models\ReportReason',
            'migration' => '',
            'table_filters' => '["name","desc","ordering"]',
            'table_fields' => '["name","desc","ordering"]',
            'api_fields_list' => '["name","desc","ordering"]',
            'api_fields_single' => '["name","desc","ordering"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:41:00',
        ]);
        DB::table('entities')->insert([
            'id' => 36,
            'name' => 'OrderReport',
            'slug' => 'order-reports',
            'table' => 'order_reports',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'order_id',
            'model' => 'Core\Orders\Models\OrderReport',
            'migration' => '',
            'table_filters' => '["order_id","user_id","report_reason_id","desc_location"]',
            'table_fields' => '["order_id","user_id","report_reason_id","desc_location"]',
            'api_fields_list' => '["order_id","user_id","report_reason_id","desc_location"]',
            'api_fields_single' => '["order_id","user_id","report_reason_id","desc_location"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:41:00',
        ]);
        DB::table('entities')->insert([
            'id' => 37,
            'name' => 'OrderInvoice',
            'slug' => 'order-invoices',
            'table' => 'order_invoices',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'orders',
            'orderable' => 'no',
            'orderable_key' => 'invoice_num',
            'model' => 'Core\Orders\Models\OrderInvoice',
            'migration' => '',
            'table_filters' => '["invoice_num","order_id","user_id"]',
            'table_fields' => '["invoice_num","order_id","user_id"]',
            'api_fields_list' => '["invoice_num","data","order_id","user_id"]',
            'api_fields_single' => '["invoice_num","data","order_id","user_id"]',
            'created_at' => '2025-01-07 04:10:54',
            'updated_at' => '2025-01-08 05:41:00',
        ]);
        DB::table('entities')->insert([
            'id' => 38,
            'name' => 'Worker',
            'slug' => 'workers',
            'table' => 'workers',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'workers',
            'orderable' => 'no',
            'orderable_key' => 'image',
            'model' => 'Core\Workers\Models\Worker',
            'migration' => '',
            'table_filters' => '["image","name","phone","email","years_experience","address","birth_date","hour_price","gender","status","identity","nationality_id","city_id","categories","leader_id","workdays"]',
            'table_fields' => '["image","name","phone","email","years_experience","address","birth_date","hour_price","gender","status","identity","nationality_id","city_id","categories","leader_id","workdays"]',
            'api_fields_list' => '["image","name","phone","email","years_experience","address","birth_date","hour_price","gender","status","identity","nationality_id","city_id","categories","leader_id","workdays"]',
            'api_fields_single' => '["image","name","phone","email","years_experience","address","birth_date","hour_price","gender","status","identity","nationality_id","city_id","categories","leader_id","workdays"]',
            'created_at' => '2025-01-07 04:10:55',
            'updated_at' => '2025-01-08 05:41:00',
        ]);
        DB::table('entities')->insert([
            'id' => 39,
            'name' => 'WorkerDay',
            'slug' => 'worker-days',
            'table' => 'worker_days',
            'operations' => '["list","single","create","update","delete","api-list","api-single","api-create","api-update","api-delete"]',
            'package' => 'workers',
            'orderable' => 'no',
            'orderable_key' => 'worker_id',
            'model' => 'Core\Workers\Models\WorkerDay',
            'migration' => '',
            'table_filters' => '["worker_id","date","type"]',
            'table_fields' => '["worker_id","date","type"]',
            'api_fields_list' => '["worker_id","date","type"]',
            'api_fields_single' => '["worker_id","date","type"]',
            'created_at' => '2025-01-07 04:10:55',
            'updated_at' => '2025-01-08 05:41:00',
        ]);
    }
}
