<?php

namespace Core\Categories\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Exceptions\HttpResponseException;
use Core\Settings\Traits\ApiResponse;

class ImportCategoriesRequest extends FormRequest
{
    use ApiResponse;

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
      return [ 
			 "data.*.translations.en.name"                                                           =>  ['required','string'], 
			 "data.*.translations.ar.name"                                                           =>  ['required','string'], 
			 "data.*.type"                                                                           =>  ['required','in:clothes,sales,services,maid,host'], 
			 "data.*.delivery_price"                                                                 =>  ['nullable','numeric'], 
			 "data.*.sort"                                                                           =>  ['nullable','numeric'], 
			 "data.*.is_package"                                                                     =>  ['nullable','boolean'], 
			 "data.*.status"                                                                         =>  ['nullable','in:active,not-active'], 
			 "data.*.parent_id"                                                                      =>  ['nullable','exists:categories,id'], 
			 "data.*.city_id"                                                                        =>  ['nullable','exists:cities,id'], 
			 "data.*.sub_categories"                                                                 =>  ['nullable','array'], 
			 "data.*.sub_categories.*.translations.en.name"                                          =>  ['required','string'], 
			 "data.*.sub_categories.*.translations.ar.name"                                          =>  ['required','string'], 
			 "data.*.sub_categories.*.type"                                                          =>  ['required','in:clothes,sales,services,maid,host'], 
			 "data.*.sub_categories.*.delivery_price"                                                =>  ['nullable','numeric'], 
			 "data.*.sub_categories.*.sort"                                                          =>  ['nullable','numeric'], 
			 "data.*.sub_categories.*.is_package"                                                    =>  ['nullable','boolean'], 
			 "data.*.sub_categories.*.status"                                                        =>  ['nullable','in:active,not-active'], 
			 "data.*.sub_categories.*.city_id"                                                       =>  ['nullable','exists:cities,id'], 
			 "data.*.sub_categories.*.category_types"                                                =>  ['nullable','array'], 
			 "data.*.sub_categories.*.category_types.*.translations.en.name"                         =>  ['required','string'], 
			 "data.*.sub_categories.*.category_types.*.translations.ar.name"                         =>  ['required','string'], 
			 "data.*.sub_categories.*.category_types.*.hour_price"                                   =>  ['required','numeric'], 
			 "data.*.sub_categories.*.category_types.*.status"                                       =>  ['required','in:active,not-active'], 
			 "data.*.sub_categories.*.category_settings"                                             =>  ['nullable','array'], 
			 "data.*.sub_categories.*.category_settings.*.translations.en.name"                      =>  ['required','string'], 
			 "data.*.sub_categories.*.category_settings.*.translations.ar.name"                      =>  ['required','string'], 
			 "data.*.sub_categories.*.category_settings.*.category_id"                               =>  ['required','exists:categories,id'], 
			 "data.*.sub_categories.*.category_settings.*.addon_price"                               =>  ['nullable','numeric'], 
			 "data.*.sub_categories.*.category_settings.*.status"                                    =>  ['required','in:active,not-active'], 
			 "data.*.sub_categories.*.category_settings.*.category_settings"                         =>  ['nullable','array'], 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.translations.en.name"  =>  ['required','string'], 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.translations.ar.name"  =>  ['required','string'], 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.category_id"           =>  ['required','exists:categories,id'], 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.addon_price"           =>  ['nullable','numeric'], 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.status"                =>  ['required','in:active,not-active'], 
			 "data.*.sub_categories.*.date_times"                                                    =>  ['nullable','array'], 
			 "data.*.sub_categories.*.date_times.*.date"                                             =>  ['required','date'], 
			 "data.*.sub_categories.*.date_times.*.from"                                             =>  ['required','time'], 
			 "data.*.sub_categories.*.date_times.*.to"                                               =>  ['required','time'], 
			 "data.*.sub_categories.*.date_times.*.order_count"                                      =>  ['nullable','numeric'], 
			 "data.*.category_types"                                                                 =>  ['nullable','array'], 
			 "data.*.category_types.*.translations.en.name"                                          =>  ['required','string'], 
			 "data.*.category_types.*.translations.ar.name"                                          =>  ['required','string'], 
			 "data.*.category_types.*.hour_price"                                                    =>  ['required','numeric'], 
			 "data.*.category_types.*.status"                                                        =>  ['required','in:active,not-active'], 
			 "data.*.category_settings"                                                              =>  ['nullable','array'], 
			 "data.*.category_settings.*.translations.en.name"                                       =>  ['required','string'], 
			 "data.*.category_settings.*.translations.ar.name"                                       =>  ['required','string'], 
			 "data.*.category_settings.*.category_id"                                                =>  ['required','exists:categories,id'], 
			 "data.*.category_settings.*.addon_price"                                                =>  ['nullable','numeric'], 
			 "data.*.category_settings.*.status"                                                     =>  ['required','in:active,not-active'], 
			 "data.*.category_settings.*.category_settings"                                          =>  ['nullable','array'], 
			 "data.*.category_settings.*.category_settings.*.translations.en.name"                   =>  ['required','string'], 
			 "data.*.category_settings.*.category_settings.*.translations.ar.name"                   =>  ['required','string'], 
			 "data.*.category_settings.*.category_settings.*.category_id"                            =>  ['required','exists:categories,id'], 
			 "data.*.category_settings.*.category_settings.*.addon_price"                            =>  ['nullable','numeric'], 
			 "data.*.category_settings.*.category_settings.*.status"                                 =>  ['required','in:active,not-active'], 
			 "data.*.date_times"                                                                     =>  ['nullable','array'], 
			 "data.*.date_times.*.date"                                                              =>  ['required','date'], 
			 "data.*.date_times.*.from"                                                              =>  ['required','time'], 
			 "data.*.date_times.*.to"                                                                =>  ['required','time'], 
			 "data.*.date_times.*.order_count"                                                       =>  ['nullable','numeric'], 
			]; 

    }

    /**
     * Get the error messages for the defined validation rules.
     *
     * @return array
     */
    public function messages()
    {
      return [ 
			 "data.*.slug.string"                                                                             =>  trans('slug should be a string'), 
			 "data.*.slug.required"                                                                           =>  trans('slug is required'), 
			 "data.*.slug.unique"                                                                             =>  trans('slug should be unique'), 
			 "data.*.translations.en.name.string"                                                             =>  trans('name should be a string'), 
			 "data.*.translations.en.name.required"                                                           =>  trans('name is required'), 
			 "data.*.translations.ar.name.string"                                                             =>  trans('name should be a string'), 
			 "data.*.translations.ar.name.required"                                                           =>  trans('name is required'), 
			 "data.*.type.in"                                                                                 =>  trans('type is not allowed'), 
			 "data.*.type.required"                                                                           =>  trans('type is required'), 
			 "data.*.delivery_price.numeric"                                                                  =>  trans('delivery price should be a number'), 
			 "data.*.delivery_price.required"                                                                 =>  trans('delivery price is required'), 
			 "data.*.sort.numeric"                                                                            =>  trans('sort should be a number'), 
			 "data.*.sort.required"                                                                           =>  trans('sort is required'), 
			 "data.*.is_package.boolean"                                                                      =>  trans('is package should be a boolean'), 
			 "data.*.is_package.required"                                                                     =>  trans('is package is required'), 
			 "data.*.status.in"                                                                               =>  trans('status is not allowed'), 
			 "data.*.status.required"                                                                         =>  trans('status is required'), 
			 "data.*.parent_id.exists"                                                                        =>  trans('parent is not Valid'), 
			 "data.*.parent_id.required"                                                                      =>  trans('parent is required'), 
			 "data.*.city_id.exists"                                                                          =>  trans('city is not Valid'), 
			 "data.*.city_id.required"                                                                        =>  trans('city is required'), 
			 "data.*.sub_categories.array"                                                                    =>  trans('sub categories is not array'), 
			 "data.*.sub_categories.*.slug.string"                                                            =>  trans('slug should be a string'), 
			 "data.*.sub_categories.*.slug.required"                                                          =>  trans('slug is required'), 
			 "data.*.sub_categories.*.slug.unique"                                                            =>  trans('slug should be unique'), 
			 "data.*.sub_categories.*.translations.en.name.string"                                            =>  trans('name should be a string'), 
			 "data.*.sub_categories.*.translations.en.name.required"                                          =>  trans('name is required'), 
			 "data.*.sub_categories.*.translations.ar.name.string"                                            =>  trans('name should be a string'), 
			 "data.*.sub_categories.*.translations.ar.name.required"                                          =>  trans('name is required'), 
			 "data.*.sub_categories.*.type.in"                                                                =>  trans('type is not allowed'), 
			 "data.*.sub_categories.*.type.required"                                                          =>  trans('type is required'), 
			 "data.*.sub_categories.*.delivery_price.numeric"                                                 =>  trans('delivery price should be a number'), 
			 "data.*.sub_categories.*.delivery_price.required"                                                =>  trans('delivery price is required'), 
			 "data.*.sub_categories.*.sort.numeric"                                                           =>  trans('sort should be a number'), 
			 "data.*.sub_categories.*.sort.required"                                                          =>  trans('sort is required'), 
			 "data.*.sub_categories.*.is_package.boolean"                                                     =>  trans('is package should be a boolean'), 
			 "data.*.sub_categories.*.is_package.required"                                                    =>  trans('is package is required'), 
			 "data.*.sub_categories.*.status.in"                                                              =>  trans('status is not allowed'), 
			 "data.*.sub_categories.*.status.required"                                                        =>  trans('status is required'), 
			 "data.*.sub_categories.*.parent_id.exists"                                                       =>  trans('parent is not Valid'), 
			 "data.*.sub_categories.*.parent_id.required"                                                     =>  trans('parent is required'), 
			 "data.*.sub_categories.*.city_id.exists"                                                         =>  trans('city is not Valid'), 
			 "data.*.sub_categories.*.city_id.required"                                                       =>  trans('city is required'), 
			 "data.*.sub_categories.*.category_types.array"                                                   =>  trans('category Types is not array'), 
			 "data.*.sub_categories.*.category_types.*.slug.string"                                           =>  trans('slug should be a string'), 
			 "data.*.sub_categories.*.category_types.*.slug.required"                                         =>  trans('slug is required'), 
			 "data.*.sub_categories.*.category_types.*.slug.unique"                                           =>  trans('slug should be unique'), 
			 "data.*.sub_categories.*.category_types.*.translations.en.name.string"                           =>  trans('name should be a string'), 
			 "data.*.sub_categories.*.category_types.*.translations.en.name.required"                         =>  trans('name is required'), 
			 "data.*.sub_categories.*.category_types.*.translations.ar.name.string"                           =>  trans('name should be a string'), 
			 "data.*.sub_categories.*.category_types.*.translations.ar.name.required"                         =>  trans('name is required'), 
			 "data.*.sub_categories.*.category_types.*.category_id.exists"                                    =>  trans('category is not Valid'), 
			 "data.*.sub_categories.*.category_types.*.category_id.required"                                  =>  trans('category is required'), 
			 "data.*.sub_categories.*.category_types.*.hour_price.numeric"                                    =>  trans('hour price should be a number'), 
			 "data.*.sub_categories.*.category_types.*.hour_price.required"                                   =>  trans('hour price is required'), 
			 "data.*.sub_categories.*.category_types.*.status.in"                                             =>  trans('status is not allowed'), 
			 "data.*.sub_categories.*.category_types.*.status.required"                                       =>  trans('status is required'), 
			 "data.*.sub_categories.*.category_types.required"                                                =>  trans('category Types is required'), 
			 "data.*.sub_categories.*.category_settings.array"                                                =>  trans('category settings is not array'), 
			 "data.*.sub_categories.*.category_settings.*.slug.string"                                        =>  trans('slug should be a string'), 
			 "data.*.sub_categories.*.category_settings.*.slug.required"                                      =>  trans('slug is required'), 
			 "data.*.sub_categories.*.category_settings.*.slug.unique"                                        =>  trans('slug should be unique'), 
			 "data.*.sub_categories.*.category_settings.*.translations.en.name.string"                        =>  trans('name should be a string'), 
			 "data.*.sub_categories.*.category_settings.*.translations.en.name.required"                      =>  trans('name is required'), 
			 "data.*.sub_categories.*.category_settings.*.translations.ar.name.string"                        =>  trans('name should be a string'), 
			 "data.*.sub_categories.*.category_settings.*.translations.ar.name.required"                      =>  trans('name is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_id.exists"                                 =>  trans('category is not Valid'), 
			 "data.*.sub_categories.*.category_settings.*.category_id.required"                               =>  trans('category is required'), 
			 "data.*.sub_categories.*.category_settings.*.addon_price.numeric"                                =>  trans('addon price should be a number'), 
			 "data.*.sub_categories.*.category_settings.*.addon_price.required"                               =>  trans('addon price is required'), 
			 "data.*.sub_categories.*.category_settings.*.parent_id.exists"                                   =>  trans('parent is not Valid'), 
			 "data.*.sub_categories.*.category_settings.*.parent_id.required"                                 =>  trans('parent is required'), 
			 "data.*.sub_categories.*.category_settings.*.status.in"                                          =>  trans('status is not allowed'), 
			 "data.*.sub_categories.*.category_settings.*.status.required"                                    =>  trans('status is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.array"                            =>  trans('category settings is not array'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.slug.string"                    =>  trans('slug should be a string'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.slug.required"                  =>  trans('slug is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.slug.unique"                    =>  trans('slug should be unique'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.translations.en.name.string"    =>  trans('name should be a string'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.translations.en.name.required"  =>  trans('name is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.translations.ar.name.string"    =>  trans('name should be a string'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.translations.ar.name.required"  =>  trans('name is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.category_id.exists"             =>  trans('category is not Valid'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.category_id.required"           =>  trans('category is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.addon_price.numeric"            =>  trans('addon price should be a number'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.addon_price.required"           =>  trans('addon price is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.parent_id.exists"               =>  trans('parent is not Valid'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.parent_id.required"             =>  trans('parent is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.status.in"                      =>  trans('status is not allowed'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.*.status.required"                =>  trans('status is required'), 
			 "data.*.sub_categories.*.category_settings.*.category_settings.required"                         =>  trans('category settings is required'), 
			 "data.*.sub_categories.*.category_settings.required"                                             =>  trans('category settings is required'), 
			 "data.*.sub_categories.*.date_times.array"                                                       =>  trans('date times is not array'), 
			 "data.*.sub_categories.*.date_times.*.category_id.exists"                                        =>  trans('category is not Valid'), 
			 "data.*.sub_categories.*.date_times.*.category_id.required"                                      =>  trans('category is required'), 
			 "data.*.sub_categories.*.date_times.*.date.date"                                                 =>  trans('date should be a date'), 
			 "data.*.sub_categories.*.date_times.*.date.required"                                             =>  trans('date is required'), 
			 "data.*.sub_categories.*.date_times.*.from.time"                                                 =>  trans('from should be a time'), 
			 "data.*.sub_categories.*.date_times.*.from.required"                                             =>  trans('from is required'), 
			 "data.*.sub_categories.*.date_times.*.to.time"                                                   =>  trans('to should be a time'), 
			 "data.*.sub_categories.*.date_times.*.to.required"                                               =>  trans('to is required'), 
			 "data.*.sub_categories.*.date_times.*.order_count.numeric"                                       =>  trans('order count should be a number'), 
			 "data.*.sub_categories.*.date_times.*.order_count.required"                                      =>  trans('order count is required'), 
			 "data.*.sub_categories.*.date_times.required"                                                    =>  trans('date times is required'), 
			 "data.*.sub_categories.required"                                                                 =>  trans('sub categories is required'), 
			 "data.*.category_types.array"                                                                    =>  trans('category Types is not array'), 
			 "data.*.category_types.*.slug.string"                                                            =>  trans('slug should be a string'), 
			 "data.*.category_types.*.slug.required"                                                          =>  trans('slug is required'), 
			 "data.*.category_types.*.slug.unique"                                                            =>  trans('slug should be unique'), 
			 "data.*.category_types.*.translations.en.name.string"                                            =>  trans('name should be a string'), 
			 "data.*.category_types.*.translations.en.name.required"                                          =>  trans('name is required'), 
			 "data.*.category_types.*.translations.ar.name.string"                                            =>  trans('name should be a string'), 
			 "data.*.category_types.*.translations.ar.name.required"                                          =>  trans('name is required'), 
			 "data.*.category_types.*.category_id.exists"                                                     =>  trans('category is not Valid'), 
			 "data.*.category_types.*.category_id.required"                                                   =>  trans('category is required'), 
			 "data.*.category_types.*.hour_price.numeric"                                                     =>  trans('hour price should be a number'), 
			 "data.*.category_types.*.hour_price.required"                                                    =>  trans('hour price is required'), 
			 "data.*.category_types.*.status.in"                                                              =>  trans('status is not allowed'), 
			 "data.*.category_types.*.status.required"                                                        =>  trans('status is required'), 
			 "data.*.category_types.required"                                                                 =>  trans('category Types is required'), 
			 "data.*.category_settings.array"                                                                 =>  trans('category settings is not array'), 
			 "data.*.category_settings.*.slug.string"                                                         =>  trans('slug should be a string'), 
			 "data.*.category_settings.*.slug.required"                                                       =>  trans('slug is required'), 
			 "data.*.category_settings.*.slug.unique"                                                         =>  trans('slug should be unique'), 
			 "data.*.category_settings.*.translations.en.name.string"                                         =>  trans('name should be a string'), 
			 "data.*.category_settings.*.translations.en.name.required"                                       =>  trans('name is required'), 
			 "data.*.category_settings.*.translations.ar.name.string"                                         =>  trans('name should be a string'), 
			 "data.*.category_settings.*.translations.ar.name.required"                                       =>  trans('name is required'), 
			 "data.*.category_settings.*.category_id.exists"                                                  =>  trans('category is not Valid'), 
			 "data.*.category_settings.*.category_id.required"                                                =>  trans('category is required'), 
			 "data.*.category_settings.*.addon_price.numeric"                                                 =>  trans('addon price should be a number'), 
			 "data.*.category_settings.*.addon_price.required"                                                =>  trans('addon price is required'), 
			 "data.*.category_settings.*.parent_id.exists"                                                    =>  trans('parent is not Valid'), 
			 "data.*.category_settings.*.parent_id.required"                                                  =>  trans('parent is required'), 
			 "data.*.category_settings.*.status.in"                                                           =>  trans('status is not allowed'), 
			 "data.*.category_settings.*.status.required"                                                     =>  trans('status is required'), 
			 "data.*.category_settings.*.category_settings.array"                                             =>  trans('category settings is not array'), 
			 "data.*.category_settings.*.category_settings.*.slug.string"                                     =>  trans('slug should be a string'), 
			 "data.*.category_settings.*.category_settings.*.slug.required"                                   =>  trans('slug is required'), 
			 "data.*.category_settings.*.category_settings.*.slug.unique"                                     =>  trans('slug should be unique'), 
			 "data.*.category_settings.*.category_settings.*.translations.en.name.string"                     =>  trans('name should be a string'), 
			 "data.*.category_settings.*.category_settings.*.translations.en.name.required"                   =>  trans('name is required'), 
			 "data.*.category_settings.*.category_settings.*.translations.ar.name.string"                     =>  trans('name should be a string'), 
			 "data.*.category_settings.*.category_settings.*.translations.ar.name.required"                   =>  trans('name is required'), 
			 "data.*.category_settings.*.category_settings.*.category_id.exists"                              =>  trans('category is not Valid'), 
			 "data.*.category_settings.*.category_settings.*.category_id.required"                            =>  trans('category is required'), 
			 "data.*.category_settings.*.category_settings.*.addon_price.numeric"                             =>  trans('addon price should be a number'), 
			 "data.*.category_settings.*.category_settings.*.addon_price.required"                            =>  trans('addon price is required'), 
			 "data.*.category_settings.*.category_settings.*.parent_id.exists"                                =>  trans('parent is not Valid'), 
			 "data.*.category_settings.*.category_settings.*.parent_id.required"                              =>  trans('parent is required'), 
			 "data.*.category_settings.*.category_settings.*.status.in"                                       =>  trans('status is not allowed'), 
			 "data.*.category_settings.*.category_settings.*.status.required"                                 =>  trans('status is required'), 
			 "data.*.category_settings.*.category_settings.required"                                          =>  trans('category settings is required'), 
			 "data.*.category_settings.required"                                                              =>  trans('category settings is required'), 
			 "data.*.date_times.array"                                                                        =>  trans('date times is not array'), 
			 "data.*.date_times.*.category_id.exists"                                                         =>  trans('category is not Valid'), 
			 "data.*.date_times.*.category_id.required"                                                       =>  trans('category is required'), 
			 "data.*.date_times.*.date.date"                                                                  =>  trans('date should be a date'), 
			 "data.*.date_times.*.date.required"                                                              =>  trans('date is required'), 
			 "data.*.date_times.*.from.time"                                                                  =>  trans('from should be a time'), 
			 "data.*.date_times.*.from.required"                                                              =>  trans('from is required'), 
			 "data.*.date_times.*.to.time"                                                                    =>  trans('to should be a time'), 
			 "data.*.date_times.*.to.required"                                                                =>  trans('to is required'), 
			 "data.*.date_times.*.order_count.numeric"                                                        =>  trans('order count should be a number'), 
			 "data.*.date_times.*.order_count.required"                                                       =>  trans('order count is required'), 
			 "data.*.date_times.required"                                                                     =>  trans('date times is required'), 
			]; 

    }

    protected function failedValidation(Validator $validator)
    {
      throw new HttpResponseException($this->returnValidationError($validator));
    }

}
