<?php

namespace Core\Users\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Exceptions\HttpResponseException;
use Core\Settings\Traits\ApiResponse;

class ImportUsersRequest extends FormRequest
{
    use ApiResponse;

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
      return [ 
			 "data.*.fullname"                                      =>  ['required','string'], 
			 "data.*.email"                                         =>  ['nullable','unique:users,email','email'], 
			 "data.*.email_verified_at"                             =>  ['nullable','date'], 
			 "data.*.phone"                                         =>  ['required','unique:users,phone','string'], 
			 "data.*.phone_verified_at"                             =>  ['nullable','date'], 
			 "data.*.roles"                                         =>  ['nullable','array'], 
			 "data.*.roles.*"                                       =>  ['exists:roles,id'], 
			 "data.*.is_active"                                     =>  ['nullable','boolean'], 
			 "data.*.is_allow_notify"                               =>  ['nullable','boolean'], 
			 "data.*.date_of_birth"                                 =>  ['nullable','date'], 
			 "data.*.identity_number"                               =>  ['nullable','unique:users,identity_number','string'], 
			 "data.*.wallet"                                        =>  ['nullable','numeric'], 
			 "data.*.points_balance"                                =>  ['nullable','numeric'], 
			 "data.*.gender"                                        =>  ['required','in:male,female'], 
			 "data.*.rate_avg"                                      =>  ['required','numeric'], 
			 "data.*.referral_code"                                 =>  ['nullable','string'], 
			 "data.*.verified_code"                                 =>  ['nullable','string'], 
			 "data.*.last_login_at"                                 =>  ['nullable','date'], 
			 "data.*.orders"                                        =>  ['nullable','array'], 
			 "data.*.orders.*.reference_id"                         =>  ['required','unique:orders,reference_id','string'], 
			 "data.*.orders.*.type"                                 =>  ['required','in:services,clothes,sales,maid,host'], 
			 "data.*.orders.*.status"                               =>  ['nullable','in:pending,issue,ready_to_delivered,finished'], 
			 "data.*.orders.*.pay_type"                             =>  ['nullable','in:card,cash'], 
			 "data.*.orders.*.transaction_id"                       =>  ['nullable','string'], 
			 "data.*.orders.*.days_per_week"                        =>  ['nullable','numeric'], 
			 "data.*.orders.*.days_per_week_names"                  =>  ['nullable','array'], 
			 "data.*.orders.*.days_per_week_names.*"                =>  ['in:saturday ,sunday,Monday,tuesday,wednesday,thursday,friday'], 
			 "data.*.orders.*.coupon_id"                            =>  ['nullable','exists:coupons,id'], 
			 "data.*.orders.*.order_price"                          =>  ['required','numeric'], 
			 "data.*.orders.*.delivery_price"                       =>  ['nullable','numeric'], 
			 "data.*.orders.*.total_price"                          =>  ['nullable','numeric'], 
			 "data.*.orders.*.paid"                                 =>  ['nullable','numeric'], 
			 "data.*.orders.*.is_admin_accepted"                    =>  ['nullable','boolean'], 
			 "data.*.orders.*.wallet_used"                          =>  ['nullable','boolean'], 
			 "data.*.orders.*.wallet_amount_used"                   =>  ['nullable','numeric'], 
			 "data.*.orders.*.items"                                =>  ['nullable','array'], 
			 "data.*.orders.*.items.*.product_id"                   =>  ['nullable','exists:products,id'], 
			 "data.*.orders.*.items.*.product_price"                =>  ['nullable','numeric'], 
			 "data.*.orders.*.items.*.quantity"                     =>  ['nullable','numeric'], 
			 "data.*.orders.*.items.*.width"                  		=>  ['nullable','numeric'], 
			 "data.*.orders.*.items.*.height"                  		=>  ['nullable','numeric'], 
			 "data.*.orders.*.items.*.add_by_admin"                 =>  ['nullable','email'], 
			 "data.*.orders.*.items.*.update_by_admin"              =>  ['nullable','email'], 
			 "data.*.orders.*.items.*.is_picked"                    =>  ['nullable','boolean'], 
			 "data.*.orders.*.items.*.is_delivered"                 =>  ['nullable','boolean'], 
			 "data.*.orders.*.items.*.qtyUpdates"                   =>  ['nullable','array'], 
			 "data.*.orders.*.items.*.qtyUpdates.*.from"            =>  ['nullable','numeric'], 
			 "data.*.orders.*.items.*.qtyUpdates.*.to"              =>  ['required','numeric'], 
			 "data.*.orders.*.items.*.qtyUpdates.*.updater_email"   =>  ['nullable','email'], 
			 "data.*.orders.*.representatives"                      =>  ['nullable','array'], 
			 "data.*.orders.*.representatives.*.representative_id"  =>  ['required','exists:users,id'], 
			 "data.*.orders.*.representatives.*.type"               =>  ['nullable','in:delivery,technical,receiver'], 
			 "data.*.orders.*.representatives.*.date"               =>  ['nullable','date'], 
			 "data.*.orders.*.representatives.*.time"               =>  ['nullable','time'], 
			 "data.*.orders.*.representatives.*.to_time"            =>  ['nullable','time'], 
			 "data.*.orders.*.representatives.*.lat"                =>  ['nullable','string'], 
			 "data.*.orders.*.representatives.*.lng"                =>  ['nullable','string'], 
			 "data.*.orders.*.representatives.*.location"           =>  ['nullable','string'], 
			 "data.*.orders.*.representatives.*.has_problem"        =>  ['nullable','boolean'], 
			 "data.*.orders.*.representatives.*.for_all_items"      =>  ['nullable','boolean'], 
			 "data.*.orders.*.representatives.*.items"              =>  ['nullable','array'], 
			 "data.*.orders.*.representatives.*.items.*"            =>  ['exists:order_items,id'], 
			 "data.*.orders.*.reports"                              =>  ['nullable','array'], 
			 "data.*.orders.*.reports.*.user_id"                    =>  ['required','exists:users,id'], 
			 "data.*.orders.*.reports.*.report_reason_id"           =>  ['required','exists:report_reasons,id'], 
			 "data.*.orders.*.more_data"                            =>  ['nullable','array'], 
			 "data.*.orders.*.more_data.*.key"                      =>  ['required','string'], 
			 "data.*.walletTransactions"                            =>  ['nullable','array'], 
			 "data.*.walletTransactions.*.type"                     =>  ['required','in:deposit,withdraw'], 
			 "data.*.walletTransactions.*.amount"                   =>  ['required','numeric'], 
			 "data.*.walletTransactions.*.wallet_before"            =>  ['required','numeric'], 
			 "data.*.walletTransactions.*.wallet_after"             =>  ['required','numeric'], 
			 "data.*.walletTransactions.*.status"                   =>  ['required','in:accepted,rejected'], 
			 "data.*.walletTransactions.*.transaction_id"           =>  ['nullable','string'], 
			 "data.*.walletTransactions.*.bank_name"                =>  ['nullable','string'], 
			 "data.*.walletTransactions.*.account_number"           =>  ['nullable','string'], 
			 "data.*.walletTransactions.*.iban_number"              =>  ['nullable','string'], 
			 "data.*.walletTransactions.*.added_by_id"              =>  ['nullable','exists:users,id'], 
			 "data.*.walletTransactions.*.package_id"               =>  ['nullable','exists:wallet_packages,id'], 
			 "data.*.points"                                        =>  ['nullable','array'], 
			 "data.*.points.*.title"                                =>  ['required','string'], 
			 "data.*.points.*.amount"                               =>  ['required','string'], 
			 "data.*.points.*.operation"                            =>  ['required','in:withdraw,deposit'], 
			 "data.*.points.*.expire_at"                            =>  ['nullable','date'], 
			 "data.*.addresses"                                     =>  ['nullable','array'], 
			 "data.*.addresses.*.location"                          =>  ['required','string'], 
			 "data.*.addresses.*.lat"                               =>  ['nullable','string'], 
			 "data.*.addresses.*.lng"                               =>  ['nullable','string'], 
			 "data.*.addresses.*.city_id"                           =>  ['required','exists:cities,id'], 
			 "data.*.addresses.*.district_id"                       =>  ['required','exists:districts,id'], 
			]; 

    }

    /**
     * Get the error messages for the defined validation rules.
     *
     * @return array
     */
    public function messages()
    {
      return [ 
			 "data.*.fullname.string"                                        =>  trans('full name should be a string'), 
			 "data.*.fullname.required"                                      =>  trans('full name is required'), 
			 "data.*.email.email"                                            =>  trans('email should be a email'), 
			 "data.*.email.required"                                         =>  trans('email is required'), 
			 "data.*.email.unique"                                           =>  trans('email should be unique'), 
			 "data.*.email_verified_at.date"                                 =>  trans('email verified at should be a date'), 
			 "data.*.email_verified_at.required"                             =>  trans('email verified at is required'), 
			 "data.*.phone.string"                                           =>  trans('phone should be a string'), 
			 "data.*.phone.required"                                         =>  trans('phone is required'), 
			 "data.*.phone.unique"                                           =>  trans('phone should be unique'), 
			 "data.*.phone_verified_at.date"                                 =>  trans('phone verified at should be a date'), 
			 "data.*.phone_verified_at.required"                             =>  trans('phone verified at is required'), 
			 "data.*.roles.array"                                            =>  trans('roles is not array'), 
			 "data.*.roles.*.exists.*"                                       =>  trans('roles is not Valid'), 
			 "data.*.roles.required"                                         =>  trans('roles is required'), 
			 "data.*.is_active.boolean"                                      =>  trans('is active should be a boolean'), 
			 "data.*.is_active.required"                                     =>  trans('is active is required'), 
			 "data.*.is_allow_notify.boolean"                                =>  trans('is allow notify should be a boolean'), 
			 "data.*.is_allow_notify.required"                               =>  trans('is allow notify is required'), 
			 "data.*.date_of_birth.date"                                     =>  trans('date of birth should be a date'), 
			 "data.*.date_of_birth.required"                                 =>  trans('date of birth is required'), 
			 "data.*.identity_number.string"                                 =>  trans('identity number should be a string'), 
			 "data.*.identity_number.required"                               =>  trans('identity number is required'), 
			 "data.*.identity_number.unique"                                 =>  trans('identity number should be unique'), 
			 "data.*.wallet.numeric"                                         =>  trans('wallet should be a number'), 
			 "data.*.wallet.required"                                        =>  trans('wallet is required'), 
			 "data.*.points_balance.numeric"                                 =>  trans('points balance should be a number'), 
			 "data.*.points_balance.required"                                =>  trans('points balance is required'), 
			 "data.*.gender.in"                                              =>  trans('gender is not allowed'), 
			 "data.*.gender.required"                                        =>  trans('gender is required'), 
			 "data.*.rate_avg.numeric"                                       =>  trans('rate avg should be a number'), 
			 "data.*.rate_avg.required"                                      =>  trans('rate avg is required'), 
			 "data.*.referral_code.string"                                   =>  trans('referral code should be a string'), 
			 "data.*.referral_code.required"                                 =>  trans('referral code is required'), 
			 "data.*.verified_code.string"                                   =>  trans('verified code should be a string'), 
			 "data.*.verified_code.required"                                 =>  trans('verified code is required'), 
			 "data.*.last_login_at.date"                                     =>  trans('last login at should be a date'), 
			 "data.*.last_login_at.required"                                 =>  trans('last login at is required'), 
			 "data.*.orders.array"                                           =>  trans('orders is not array'), 
			 "data.*.orders.*.reference_id.string"                           =>  trans('reference_id should be a string'), 
			 "data.*.orders.*.reference_id.required"                         =>  trans('reference_id is required'), 
			 "data.*.orders.*.reference_id.unique"                           =>  trans('reference_id should be unique'), 
			 "data.*.orders.*.type.in"                                       =>  trans('type is not allowed'), 
			 "data.*.orders.*.type.required"                                 =>  trans('type is required'), 
			 "data.*.orders.*.status.in"                                     =>  trans('status is not allowed'), 
			 "data.*.orders.*.status.required"                               =>  trans('status is required'), 
			 "data.*.orders.*.client_id.exists"                              =>  trans('client is not Valid'), 
			 "data.*.orders.*.client_id.required"                            =>  trans('client is required'), 
			 "data.*.orders.*.pay_type.in"                                   =>  trans('pay type is not allowed'), 
			 "data.*.orders.*.pay_type.required"                             =>  trans('pay type is required'), 
			 "data.*.orders.*.transaction_id.string"                         =>  trans('transaction id should be a string'), 
			 "data.*.orders.*.transaction_id.required"                       =>  trans('transaction id is required'), 
			 "data.*.orders.*.days_per_week.numeric"                         =>  trans('days per week should be a number'), 
			 "data.*.orders.*.days_per_week.required"                        =>  trans('days per week is required'), 
			 "data.*.orders.*.days_per_week_names.array"                     =>  trans('days per week names is not array'), 
			 "data.*.orders.*.days_per_week_names.*.in.*"                    =>  trans('days per week names is not allowed'), 
			 "data.*.orders.*.days_per_week_names.required"                  =>  trans('days per week names is required'), 
			 "data.*.orders.*.coupon_id.exists"                              =>  trans('coupon is not Valid'), 
			 "data.*.orders.*.coupon_id.required"                            =>  trans('coupon is required'), 
			 "data.*.orders.*.order_price.numeric"                           =>  trans('order price  should be a number'), 
			 "data.*.orders.*.order_price.required"                          =>  trans('order price  is required'), 
			 "data.*.orders.*.delivery_price.numeric"                        =>  trans('delivery price  should be a number'), 
			 "data.*.orders.*.delivery_price.required"                       =>  trans('delivery price  is required'), 
			 "data.*.orders.*.total_price.numeric"                           =>  trans('total price should be a number'), 
			 "data.*.orders.*.total_price.required"                          =>  trans('total price is required'), 
			 "data.*.orders.*.paid.numeric"                                  =>  trans('paid should be a number'), 
			 "data.*.orders.*.paid.required"                                 =>  trans('paid is required'), 
			 "data.*.orders.*.is_admin_accepted.boolean"                     =>  trans('is admin accepted should be a boolean'), 
			 "data.*.orders.*.is_admin_accepted.required"                    =>  trans('is admin accepted is required'), 
			 "data.*.orders.*.wallet_used.boolean"                           =>  trans('wallet used should be a boolean'), 
			 "data.*.orders.*.wallet_used.required"                          =>  trans('wallet used is required'), 
			 "data.*.orders.*.wallet_amount_used.numeric"                    =>  trans('wallet amount used should be a number'), 
			 "data.*.orders.*.wallet_amount_used.required"                   =>  trans('wallet amount used is required'), 
			 "data.*.orders.*.items.array"                                   =>  trans('items is not array'), 
			 "data.*.orders.*.items.*.order_id.exists"                       =>  trans('order is not Valid'), 
			 "data.*.orders.*.items.*.order_id.required"                     =>  trans('order is required'), 
			 "data.*.orders.*.items.*.product_id.exists"                     =>  trans('product is not Valid'), 
			 "data.*.orders.*.items.*.product_id.required"                   =>  trans('product is required'), 
			 "data.*.orders.*.items.*.product_price.numeric"                 =>  trans('product price should be a number'), 
			 "data.*.orders.*.items.*.product_price.required"                =>  trans('product price is required'), 
			 "data.*.orders.*.items.*.quantity.numeric"                      =>  trans('quantity should be a number'), 
			 "data.*.orders.*.items.*.quantity.required"                     =>  trans('quantity is required'), 
			 "data.*.orders.*.items.*.width.numeric"                   		=>  trans('width should be a number'), 
			 "data.*.orders.*.items.*.width.required"                  		=>  trans('width is required'), 
			 "data.*.orders.*.items.*.height.numeric"                   	=>  trans('height should be a number'), 
			 "data.*.orders.*.items.*.height.required"                  	=>  trans('height is required'), 
			 "data.*.orders.*.items.*.add_by_admin.email"                    =>  trans('add by admin should be a email'), 
			 "data.*.orders.*.items.*.add_by_admin.required"                 =>  trans('add by admin is required'), 
			 "data.*.orders.*.items.*.update_by_admin.email"                 =>  trans('update by admin should be a email'), 
			 "data.*.orders.*.items.*.update_by_admin.required"              =>  trans('update by admin is required'), 
			 "data.*.orders.*.items.*.is_picked.boolean"                     =>  trans('is picked should be a boolean'), 
			 "data.*.orders.*.items.*.is_picked.required"                    =>  trans('is picked is required'), 
			 "data.*.orders.*.items.*.is_delivered.boolean"                  =>  trans('is delivered should be a boolean'), 
			 "data.*.orders.*.items.*.is_delivered.required"                 =>  trans('is delivered is required'), 
			 "data.*.orders.*.items.*.qtyUpdates.array"                      =>  trans('qtyUpdates is not array'), 
			 "data.*.orders.*.items.*.qtyUpdates.*.item_id.exists"           =>  trans('item is not Valid'), 
			 "data.*.orders.*.items.*.qtyUpdates.*.item_id.required"         =>  trans('item is required'), 
			 "data.*.orders.*.items.*.qtyUpdates.*.from.numeric"             =>  trans('from should be a number'), 
			 "data.*.orders.*.items.*.qtyUpdates.*.from.required"            =>  trans('from is required'), 
			 "data.*.orders.*.items.*.qtyUpdates.*.to.numeric"               =>  trans('to should be a number'), 
			 "data.*.orders.*.items.*.qtyUpdates.*.to.required"              =>  trans('to is required'), 
			 "data.*.orders.*.items.*.qtyUpdates.*.updater_email.email"      =>  trans('updater email should be a email'), 
			 "data.*.orders.*.items.*.qtyUpdates.*.updater_email.required"   =>  trans('updater email is required'), 
			 "data.*.orders.*.items.*.qtyUpdates.required"                   =>  trans('qtyUpdates is required'), 
			 "data.*.orders.*.items.required"                                =>  trans('items is required'), 
			 "data.*.orders.*.representatives.array"                         =>  trans('representatives is not array'), 
			 "data.*.orders.*.representatives.*.order_id.exists"             =>  trans('order is not Valid'), 
			 "data.*.orders.*.representatives.*.order_id.required"           =>  trans('order is required'), 
			 "data.*.orders.*.representatives.*.representative_id.exists"    =>  trans('representative is not Valid'), 
			 "data.*.orders.*.representatives.*.representative_id.required"  =>  trans('representative is required'), 
			 "data.*.orders.*.representatives.*.type.in"                     =>  trans('type is not allowed'), 
			 "data.*.orders.*.representatives.*.type.required"               =>  trans('type is required'), 
			 "data.*.orders.*.representatives.*.date.date"                   =>  trans('date should be a date'), 
			 "data.*.orders.*.representatives.*.date.required"               =>  trans('date is required'), 
			 "data.*.orders.*.representatives.*.time.time"                   =>  trans('time should be a time'), 
			 "data.*.orders.*.representatives.*.time.required"               =>  trans('time is required'), 
			 "data.*.orders.*.representatives.*.to_time.time"                =>  trans('to time should be a time'), 
			 "data.*.orders.*.representatives.*.to_time.required"            =>  trans('to time is required'), 
			 "data.*.orders.*.representatives.*.lat.string"                  =>  trans('lat should be a string'), 
			 "data.*.orders.*.representatives.*.lat.required"                =>  trans('lat is required'), 
			 "data.*.orders.*.representatives.*.lng.string"                  =>  trans('lng should be a string'), 
			 "data.*.orders.*.representatives.*.lng.required"                =>  trans('lng is required'), 
			 "data.*.orders.*.representatives.*.location.string"             =>  trans('location should be a string'), 
			 "data.*.orders.*.representatives.*.location.required"           =>  trans('location is required'), 
			 "data.*.orders.*.representatives.*.has_problem.boolean"         =>  trans('has problem should be a boolean'), 
			 "data.*.orders.*.representatives.*.has_problem.required"        =>  trans('has problem is required'), 
			 "data.*.orders.*.representatives.*.for_all_items.boolean"       =>  trans('for_all items should be a boolean'), 
			 "data.*.orders.*.representatives.*.for_all_items.required"      =>  trans('for_all items is required'), 
			 "data.*.orders.*.representatives.*.items.array"                 =>  trans('items is not array'), 
			 "data.*.orders.*.representatives.*.items.*.exists.*"            =>  trans('items is not Valid'), 
			 "data.*.orders.*.representatives.*.items.required"              =>  trans('items is required'), 
			 "data.*.orders.*.representatives.required"                      =>  trans('representatives is required'), 
			 "data.*.orders.*.reports.array"                                 =>  trans('reports is not array'), 
			 "data.*.orders.*.reports.*.order_id.exists"                     =>  trans('order is not Valid'), 
			 "data.*.orders.*.reports.*.order_id.required"                   =>  trans('order is required'), 
			 "data.*.orders.*.reports.*.user_id.exists"                      =>  trans('user is not Valid'), 
			 "data.*.orders.*.reports.*.user_id.required"                    =>  trans('user is required'), 
			 "data.*.orders.*.reports.*.report_reason_id.exists"             =>  trans('report reason is not Valid'), 
			 "data.*.orders.*.reports.*.report_reason_id.required"           =>  trans('report reason is required'), 
			 "data.*.orders.*.reports.required"                              =>  trans('reports is required'), 
			 "data.*.orders.*.more_data.array"                               =>  trans('more Data is not array'), 
			 "data.*.orders.*.more_data.*.order_id.exists"                   =>  trans('order is not Valid'), 
			 "data.*.orders.*.more_data.*.order_id.required"                 =>  trans('order is required'), 
			 "data.*.orders.*.more_data.*.key.string"                        =>  trans('key should be a string'), 
			 "data.*.orders.*.more_data.*.key.required"                      =>  trans('key is required'), 
			 "data.*.orders.*.more_data.required"                            =>  trans('more Data is required'), 
			 "data.*.orders.required"                                        =>  trans('orders is required'), 
			 "data.*.walletTransactions.array"                               =>  trans('wallet Transactions is not array'), 
			 "data.*.walletTransactions.*.type.in"                           =>  trans('type is not allowed'), 
			 "data.*.walletTransactions.*.type.required"                     =>  trans('type is required'), 
			 "data.*.walletTransactions.*.amount.numeric"                    =>  trans('amount should be a number'), 
			 "data.*.walletTransactions.*.amount.required"                   =>  trans('amount is required'), 
			 "data.*.walletTransactions.*.wallet_before.numeric"             =>  trans('wallet before should be a number'), 
			 "data.*.walletTransactions.*.wallet_before.required"            =>  trans('wallet before is required'), 
			 "data.*.walletTransactions.*.wallet_after.numeric"              =>  trans('wallet after should be a number'), 
			 "data.*.walletTransactions.*.wallet_after.required"             =>  trans('wallet after is required'), 
			 "data.*.walletTransactions.*.status.in"                         =>  trans('status is not allowed'), 
			 "data.*.walletTransactions.*.status.required"                   =>  trans('status is required'), 
			 "data.*.walletTransactions.*.transaction_id.string"             =>  trans('transaction id should be a string'), 
			 "data.*.walletTransactions.*.transaction_id.required"           =>  trans('transaction id is required'), 
			 "data.*.walletTransactions.*.bank_name.string"                  =>  trans('bank name should be a string'), 
			 "data.*.walletTransactions.*.bank_name.required"                =>  trans('bank name is required'), 
			 "data.*.walletTransactions.*.account_number.string"             =>  trans('account number should be a string'), 
			 "data.*.walletTransactions.*.account_number.required"           =>  trans('account number is required'), 
			 "data.*.walletTransactions.*.iban_number.string"                =>  trans('iban number should be a string'), 
			 "data.*.walletTransactions.*.iban_number.required"              =>  trans('iban number is required'), 
			 "data.*.walletTransactions.*.user_id.exists"                    =>  trans('user is not Valid'), 
			 "data.*.walletTransactions.*.user_id.required"                  =>  trans('user is required'), 
			 "data.*.walletTransactions.*.added_by_id.exists"                =>  trans('added by is not Valid'), 
			 "data.*.walletTransactions.*.added_by_id.required"              =>  trans('added by is required'), 
			 "data.*.walletTransactions.*.package_id.exists"                 =>  trans('package is not Valid'), 
			 "data.*.walletTransactions.*.package_id.required"               =>  trans('package is required'), 
			 "data.*.walletTransactions.required"                            =>  trans('wallet Transactions is required'), 
			 "data.*.points.array"                                           =>  trans('points is not array'), 
			 "data.*.points.*.title.string"                                  =>  trans('title should be a string'), 
			 "data.*.points.*.title.required"                                =>  trans('title is required'), 
			 "data.*.points.*.amount.string"                                 =>  trans('amount should be a string'), 
			 "data.*.points.*.amount.required"                               =>  trans('amount is required'), 
			 "data.*.points.*.operation.in"                                  =>  trans('operation is not allowed'), 
			 "data.*.points.*.operation.required"                            =>  trans('operation is required'), 
			 "data.*.points.*.expire_at.date"                                =>  trans('expire at should be a date'), 
			 "data.*.points.*.expire_at.required"                            =>  trans('expire at is required'), 
			 "data.*.points.*.user_id.exists"                                =>  trans('user is not Valid'), 
			 "data.*.points.*.user_id.required"                              =>  trans('user is required'), 
			 "data.*.points.required"                                        =>  trans('points is required'), 
			 "data.*.addresses.array"                                        =>  trans('addresses is not array'), 
			 "data.*.addresses.*.location.string"                            =>  trans('location should be a string'), 
			 "data.*.addresses.*.location.required"                          =>  trans('location is required'), 
			 "data.*.addresses.*.lat.string"                                 =>  trans('lat should be a string'), 
			 "data.*.addresses.*.lat.required"                               =>  trans('lat is required'), 
			 "data.*.addresses.*.lng.string"                                 =>  trans('lng should be a string'), 
			 "data.*.addresses.*.lng.required"                               =>  trans('lng is required'), 
			 "data.*.addresses.*.city_id.exists"                             =>  trans('city is not Valid'), 
			 "data.*.addresses.*.city_id.required"                           =>  trans('city is required'), 
			 "data.*.addresses.*.district_id.exists"                         =>  trans('district is not Valid'), 
			 "data.*.addresses.*.district_id.required"                       =>  trans('district is required'), 
			 "data.*.addresses.*.user_id.exists"                             =>  trans('user is not Valid'), 
			 "data.*.addresses.*.user_id.required"                           =>  trans('user is required'), 
			 "data.*.addresses.required"                                     =>  trans('addresses is required'), 
			]; 

    }

    protected function failedValidation(Validator $validator)
    {
      throw new HttpResponseException($this->returnValidationError($validator));
    }

}
